apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: skysfather
            - name: POSTGRES_USER
              value: skysfather
            - name: POSTGRES_PASSWORD
              value: skysfather
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: db-service
  ports:
    - port: 5432
      targetPort: 5432
